version: '3.9'

services:
  postgres:
    image: docker.io/postgres:16
    container_name: postgres16
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: yourStrongPassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "developer"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
